### ISSUE TITLE
Exception when no kext specified

### ISSUE THREAD

**Issue by mc-17** [blacktop/ipsw#212]
omitting the `-a` flag and any kexts doesn't scold me like a naughty schoolboy caught stealing food but instead throws an exception

command: `ipsw kernel extract 20D67__iPhone15,2/kernelcache.release.iPhone15,2`

```
me@me ~ % ipsw kernel extract 20D67__iPhone15,2/kernelcache.release.iPhone15,2
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/blacktop/ipsw/cmd/ipsw/cmd/kernel.glob..func7(0x102f35100?, {0x140003b40f0, 0x1, 0x1?})
	github.com/blacktop/ipsw/cmd/ipsw/cmd/kernel/kernel_extract.go:108 +0x5ac
github.com/spf13/cobra.(*Command).execute(0x102f35100, {0x140003b40c0, 0x1, 0x1})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c4
github.com/spf13/cobra.(*Command).ExecuteC(0x102f19c00)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/blacktop/ipsw/cmd/ipsw/cmd.Execute()
	github.com/blacktop/ipsw/cmd/ipsw/cmd/root.go:64 +0x24
main.main()
	github.com/blacktop/ipsw/cmd/ipsw/main.go:27 +0x1c
```

**Comment by blacktop** [comment]
Thanks for letting me know @mc-17 ! I'll look into it.

**Comment by blacktop** [comment]
Cutting release now w/ fix. Many thanks!! 👍

**Comment by n0thing2speak** [comment]
> Cutting release now w/ fix. Many thanks!! 👍

```
ipsw kernel extract --all 20D67__iPhone10,3_6/kernelcache.release.iPhone10,3_6
   ⨯ kernelcache type is not MH_FILESET (KEXT-xtraction not supported yet)
```
Is this a bug?
