### ISSUE TITLE
ipsw diff: panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by pwmoore** [blacktop/ipsw#213]
I saw that a `diff` command was added to `ipsw` and I was excited to try it out, especially with the release of iOS 16.4. I updated `ipsw`, then downloaded the latest firmware and ran the command:

```
$ ipsw diff iPhone12,3,iPhone12,5_16.3.1_20D67_Restore.ipsw iPhone12,3,iPhone12,5_16.4_20E247_Restore.ipsw
```
Unfortunately, `ipsw` panicked with the following error:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/blacktop/ipsw/internal/diff.New(...)
        /Users/pwm/git/ipsw/internal/diff/diff.go:66
github.com/blacktop/ipsw/cmd/ipsw/cmd.glob..func6(0x101f32f80?, {0xc000340d20, 0x2, 0x2?})
        /Users/pwm/git/ipsw/cmd/ipsw/cmd/diff.go:63 +0x456
github.com/spf13/cobra.(*Command).execute(0x101f32f80, {0xc000340ce0, 0x2, 0x2})
        /Users/pwm/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x101f34680)
        /Users/pwm/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/pwm/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/blacktop/ipsw/cmd/ipsw/cmd.Execute()
        /Users/pwm/git/ipsw/cmd/ipsw/cmd/root.go:64 +0x25
main.main()
        /Users/pwm/git/ipsw/cmd/ipsw/main.go:27 +0x17
```

As a test, I also downloaded 16.2 for the same device, thinking there might be something wrong with the 16.4 IPSW file, but I got the same issue.

I fully admit this could be user error on my part as well, so if this is the case, feel free to yell at me to RTFM.

Thanks!

**Comment by blacktop** [comment]
Many thanks, this is a legit error (I added KDK diffing at the last moment and didn't test running the cmd w/o supplying the `--kdk` flags 🤦

**Comment by blacktop** [comment]
fix is out now in latest release. let me know how it goes 👍

**Comment by blacktop** [comment]
Once again some great suggestions!
