### ISSUE TITLE
`ipsw diff` mount failure on iPhone ipsw

### ISSUE THREAD

**Issue by clearbluejar** [blacktop/ipsw#384]
### What happened?

```zsh
ipsw diff iPhone14,7_16.4.1_20E252_Restore.ipsw iPhone14,7_16.5_20F66_Restore.ipsw -V > iPhone14,7_16.4.1_20E252-iPhone14,7_16.5_20F66.ipsw.diff.md
   • Diffing KERNELCACHES
      • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache2292932949/kernelcache.release.iphone14b from iPhone14,7_16.4.1_20E252_Restore.ipsw
      • Parsing Kernelcache IMG4
      • Decompressing Kernelcache
         • Kernelcache is LZFSE compressed
      • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache101466256/kernelcache.release.iphone14b from iPhone14,7_16.5_20F66_Restore.ipsw
      • Parsing Kernelcache IMG4
      • Decompressing Kernelcache
         • Kernelcache is LZFSE compressed
   • Diffing DYLD_SHARED_CACHES
   • Mounting 'Old' SystemOS DMG
      • Extracted 078-24368-347.dmg from iPhone14,7_16.4.1_20E252_Restore.ipsw
panic: flate: corrupt input before offset 628560804

goroutine 1 [running]:
github.com/blacktop/ipsw/internal/utils.Unzip.func2.1()
	github.com/blacktop/ipsw/internal/utils/utils.go:296 +0x44
github.com/blacktop/ipsw/internal/utils.Unzip.func2(0x140010dc2c0)
	github.com/blacktop/ipsw/internal/utils/utils.go:319 +0x2d8
github.com/blacktop/ipsw/internal/utils.Unzip({0x16b94391a, 0x25}, {0x0, 0x0}, 0x140011059d8)
	github.com/blacktop/ipsw/internal/utils/utils.go:328 +0x268
github.com/blacktop/ipsw/internal/diff.mountDMG(0x140005de6d0)
	github.com/blacktop/ipsw/internal/diff/diff.go:226 +0xf0
github.com/blacktop/ipsw/internal/diff.(*Diff).mountSystemOsDMGs(0x140005de6c0)
	github.com/blacktop/ipsw/internal/diff/diff.go:253 +0x58
github.com/blacktop/ipsw/internal/diff.(*Diff).Diff(0x140005de6c0, 0x0)
	github.com/blacktop/ipsw/internal/diff/diff.go:190 +0x270
github.com/blacktop/ipsw/cmd/ipsw/cmd.glob..func9(0x140004bbc00?, {0x14000124960, 0x2, 0x105ffe285?})
	github.com/blacktop/ipsw/cmd/ipsw/cmd/diff.go:77 +0x36c
github.com/spf13/cobra.(*Command).execute(0x107237760, {0x140001248d0, 0x3, 0x3})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x107239fa0)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/blacktop/ipsw/cmd/ipsw/cmd.Execute()
	github.com/blacktop/ipsw/cmd/ipsw/cmd/root.go:70 +0x24
main.main()
	github.com/blacktop/ipsw/cmd/ipsw/main.go:27 +0x1c
```

### How can we reproduce this?

```zsh
ipsw download ipsw --device iPhone14,7 -b 20E252
ipsw download ipsw --device iPhone14,7 -b 20F66
ipsw diff iPhone14,7_16.4.1_20E252_Restore.ipsw iPhone14,7_16.5_20F66_Restore.ipsw -V
```

### ipsw version

```bash
Version: 3.1.437, BuildTime: 2023-12-19T05:42:00Z
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I repeated the command with the latest version:
`Version: 3.1.445, BuildTime: 2024-01-12T03:49:13Z`

But still hit an error with a slightly different message:
```zsh
% ipsw diff iPhone14,7_16.4.1_20E252_Restore.ipsw iPhone14,7_16.5_20F66_Restore.ipsw -V > iPhone14,7_16.4.1_20E252-iPhone14,7_16.5_20F66.ipsw.diff.md
   • Diffing KERNELCACHES
      • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache22407188/kernelcache.release.iphone14b from iPhone14,7_16.4.1_20E252_Restore.ipsw
      • Parsing Kernelcache IMG4
      • Decompressing Kernelcache
         • Kernelcache is LZFSE compressed
      • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache3020894245/kernelcache.release.iphone14b from iPhone14,7_16.5_20F66_Restore.ipsw
      • Parsing Kernelcache IMG4
      • Decompressing Kernelcache
         • Kernelcache is LZFSE compressed
   • Diffing DYLD_SHARED_CACHES
   • Mounting 'Old' SystemOS DMG
      • Found extracted 078-24368-347.dmg
      • Mounting 078-24368-347.dmg
   ⨯ failed to mount DMGs: failed to mount DMG: failed to mount 078-24368-347.dmg: exit status 1: hdiutil: attach failed - image not recognized
```

Maybe this is a simple issue with the ipsw files downloaded? Let me know if I should try something else.

**Comment by blacktop** [comment]
Is this error repeatable?

It seems to be saying an error happened trying to unzip the DMG from the IPSW.  That's using the stdlib funcs so I'd think you might have a corrupt IPSW zip?

**Comment by clearbluejar** [comment]
I will try this on a new machine with new binaries.

**Comment by clearbluejar** [comment]
confirmed! this was just an IPSW file corruption. redownloading the binaries fixed it. user error. thanks!
