### ISSUE TITLE
Crash when extracting entitlement in Mac_15.0_24A5279h beta build

### ISSUE THREAD

**Issue by whiteck01** [blacktop/ipsw#502]
### What happened?

* Crash when extracting entitlement in Mac_15.0_24A5279h beta build
```
ipsw ent --ipsw ./UniversalMac_15.0_24A5279h_Restore.ipsw --ui
      • Generating entitlement database file...
         • Scanning AppOS           
         • Scanning SystemOS        
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x101115bb0]

goroutine 1 [running]:
github.com/blacktop/ipsw/pkg/aea.PrivateKey.UnmarshalBinaryPrivateKey({0x1400209e400?, 0x140033861e0?, 0x14002b48a08?})
	github.com/blacktop/ipsw/pkg/aea/aea.go:62 +0x20
github.com/blacktop/ipsw/pkg/aea.Metadata.DecryptFCS(0x14003386000, {0x0, 0x0, 0x0})
	github.com/blacktop/ipsw/pkg/aea/aea.go:146 +0x2b0
github.com/blacktop/ipsw/pkg/aea.Decrypt({0x14000138a80, 0x15}, {0x102347580, 0x1}, {0x0, 0x0, 0x0})
	github.com/blacktop/ipsw/pkg/aea/decrypt.go:262 +0x9c
github.com/blacktop/ipsw/internal/commands/ent.scanEnts({0x14000786bd0, 0x29}, {0x14000138a80, 0x15}, {0x101b591b4, 0x8})
	github.com/blacktop/ipsw/internal/commands/ent/ent.go:280 +0x340
github.com/blacktop/ipsw/internal/commands/ent.GetDatabase(0x14002b49818)
	github.com/blacktop/ipsw/internal/commands/ent/ent.go:69 +0x6e0
github.com/blacktop/ipsw/cmd/ipsw/cmd.init.func10(0x1400098da00?, {0x14000866d80?, 0x4?, 0x101b4da26?})
	github.com/blacktop/ipsw/cmd/ipsw/cmd/ent.go:174 +0x598
github.com/spf13/cobra.(*Command).execute(0x103146480, {0x14000866d20, 0x3, 0x3})
	github.com/spf13/cobra@v1.8.1/command.go:985 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x103148140)
	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/blacktop/ipsw/cmd/ipsw/cmd.Execute()
	github.com/blacktop/ipsw/cmd/ipsw/cmd/root.go:67 +0x24
main.main()
	github.com/blacktop/ipsw/cmd/ipsw/main.go:27 +0x1c

```

### How can we reproduce this?

```
ipsw ent --ipsw ./UniversalMac_15.0_24A5279h_Restore.ipsw --ui
      • Generating entitlement database file...
         • Scanning AppOS           
         • Scanning SystemOS        
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x101115bb0]

goroutine 1 [running]:
github.com/blacktop/ipsw/pkg/aea.PrivateKey.UnmarshalBinaryPrivateKey({0x1400209e400?, 0x140033861e0?, 0x14002b48a08?})
	github.com/blacktop/ipsw/pkg/aea/aea.go:62 +0x20
github.com/blacktop/ipsw/pkg/aea.Metadata.DecryptFCS(0x14003386000, {0x0, 0x0, 0x0})
	github.com/blacktop/ipsw/pkg/aea/aea.go:146 +0x2b0
github.com/blacktop/ipsw/pkg/aea.Decrypt({0x14000138a80, 0x15}, {0x102347580, 0x1}, {0x0, 0x0, 0x0})
	github.com/blacktop/ipsw/pkg/aea/decrypt.go:262 +0x9c
github.com/blacktop/ipsw/internal/commands/ent.scanEnts({0x14000786bd0, 0x29}, {0x14000138a80, 0x15}, {0x101b591b4, 0x8})
	github.com/blacktop/ipsw/internal/commands/ent/ent.go:280 +0x340
github.com/blacktop/ipsw/internal/commands/ent.GetDatabase(0x14002b49818)
	github.com/blacktop/ipsw/internal/commands/ent/ent.go:69 +0x6e0
github.com/blacktop/ipsw/cmd/ipsw/cmd.init.func10(0x1400098da00?, {0x14000866d80?, 0x4?, 0x101b4da26?})
	github.com/blacktop/ipsw/cmd/ipsw/cmd/ent.go:174 +0x598
github.com/spf13/cobra.(*Command).execute(0x103146480, {0x14000866d20, 0x3, 0x3})
	github.com/spf13/cobra@v1.8.1/command.go:985 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x103148140)
	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/blacktop/ipsw/cmd/ipsw/cmd.Execute()
	github.com/blacktop/ipsw/cmd/ipsw/cmd/root.go:67 +0x24
main.main()
	github.com/blacktop/ipsw/cmd/ipsw/main.go:27 +0x1c

```

### ipsw version

```bash
Version: 3.1.507, BuildCommit: 00d1ee8267258da3a666e65883230313030c3edb
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blacktop** [comment]
Update to latest v.308
