### ISSUE TITLE
SIGSEGV while extracting iOS 15.0.2 kernelcache

### ISSUE THREAD

**Issue by pwnee** [blacktop/ipsw#89]
Hi
First time user here. Installed v3.1.80 from brew to my MacBook Pro. Ran and got:
```
$ ipsw extract -k iPhone_4.7_P3_15.0.2_19A404_Restore.ipsw
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x45db8e2]

goroutine 1 [running]:
github.com/blacktop/ipsw/pkg/info.(*Info).GetFolder(0xc0003cdd80)
	github.com/blacktop/ipsw/pkg/info/info.go:199 +0xc2
github.com/blacktop/ipsw/cmd/ipsw/cmd.glob..func40(0x557dda0, {0xc00024b8a0, 0x1, 0x2})
	github.com/blacktop/ipsw/cmd/ipsw/cmd/extract.go:196 +0x367
github.com/spf13/cobra.(*Command).execute(0x557dda0, {0xc00024b880, 0x2, 0x2})
	github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x55814a0)
	github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.3.0/command.go:902
github.com/blacktop/ipsw/cmd/ipsw/cmd.Execute()
	github.com/blacktop/ipsw/cmd/ipsw/cmd/root.go:57 +0x25
main.main()
	github.com/blacktop/ipsw/cmd/ipsw/main.go:27 +0x17
```

**Comment by pwnee** [comment]
Tried 3.1.66 and it works

**Comment by blacktop** [comment]
what if I told you the issue was related to time zones? would you believe me? 😶‍🌫️ 😮‍💨
